"""
Feature Ideation Agent

Combines:
- Codebase capabilities (what the project can do)
- Research pain points (what users need)
- Competitive gaps (what others don't do)

To propose concrete feature ideas with:
- Clear problem statement
- Implementation approach
- Estimated effort
- Star potential
"""

import json
import subprocess
from pathlib import Path
from typing import Optional, List, Dict, Union
from datetime import datetime

from crowdmind.config import get_config


def generate_feature_ideas(
    capabilities_summary: str,
    pain_points_summary: str,
    competitors_info: str = "",
    num_ideas: int = 5,
    verbose: bool = True,
) -> List[Dict]:
    """Generate feature ideas based on research."""
    
    # Truncate inputs to avoid timeout
    capabilities_short = capabilities_summary[:2000]
    pain_points_short = pain_points_summary[:2000]
    
    prompt = f"""Propose {num_ideas} feature ideas based on this research.

CAPABILITIES:
{capabilities_short}

PAIN POINTS:
{pain_points_short}

{f"COMPETITORS: {competitors_info}" if competitors_info else ""}

Output JSON array:
```json
[
  {{
    "id": "short-name",
    "name": "Feature Name",
    "tagline": "One-line pitch",
    "problem": "Pain point solved",
    "solution": "How it solves it",
    "why_now": "Why timely",
    "differentiator": "Why unique",
    "implementation": {{
      "approach": "Technical approach",
      "components_affected": ["files"],
      "new_modules_needed": ["modules"],
      "estimated_effort": "small|medium|large",
      "complexity": "low|medium|high"
    }},
    "star_potential": {{"score": 1-10, "reasoning": "Why stars"}},
    "evidence": "Quote from research"
  }}
]
```"""

    try:
        if verbose:
            print("  Asking LLM to generate ideas...")
        
        result = subprocess.run(
            ["claude", "--print", prompt],
            capture_output=True,
            text=True,
            timeout=300
        )
        
        if result.returncode == 0:
            response = result.stdout
            import re
            json_match = re.search(r'```json\s*(.*?)\s*```', response, re.DOTALL)
            if json_match:
                ideas = json.loads(json_match.group(1))
                return ideas
    
    except Exception as e:
        print(f"Error generating ideas: {e}")
    
    return []


def save_idea_files(ideas: List[Dict], output_dir: Path, verbose: bool = True) -> List[str]:
    """Save each idea as a detailed markdown file."""
    
    output_dir.mkdir(parents=True, exist_ok=True)
    saved_files = []
    
    for idea in ideas:
        filename = f"{idea.get('id', 'unknown')}.md"
        filepath = output_dir / filename
        
        impl = idea.get('implementation', {})
        star = idea.get('star_potential', {})
        
        content = f"""# {idea.get('name', 'Unknown Feature')}

> {idea.get('tagline', '')}

## Problem
{idea.get('problem', '')}

## Solution
{idea.get('solution', '')}

## Why Now
{idea.get('why_now', '')}

## Competitive Advantage
{idea.get('differentiator', '')}

## Implementation

**Approach:** {impl.get('approach', '')}

**Effort:** {impl.get('estimated_effort', 'unknown')} | **Complexity:** {impl.get('complexity', 'unknown')}

**Components Affected:**
{chr(10).join(f'- `{c}`' for c in impl.get('components_affected', []))}

**New Modules Needed:**
{chr(10).join(f'- `{m}`' for m in impl.get('new_modules_needed', []))}

## Star Potential

**Score:** {star.get('score', 0)}/10

**Reasoning:** {star.get('reasoning', '')}

## Evidence from Research

> {idea.get('evidence', 'No direct quote')}

---
*Generated by CrowdMind Feature Ideation*
*{datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""
        
        filepath.write_text(content)
        saved_files.append(str(filepath))
        
        if verbose:
            print(f"  Saved: {filepath.name}")
    
    return saved_files


def run_ideation(
    project_path: Optional[Union[str, Path]] = None,
    num_ideas: int = 5,
    use_cache: bool = False,
    verbose: bool = True,
    capabilities_summary: Optional[str] = None,
    pain_points_summary: Optional[str] = None,
) -> Dict:
    """
    Run full ideation process.
    
    Args:
        project_path: Path to project (for codebase analysis)
        num_ideas: Number of ideas to generate
        use_cache: Use cached ideas if available
        verbose: Print progress
        capabilities_summary: Pre-computed capabilities (overrides project_path)
        pain_points_summary: Pre-computed pain points (overrides research)
    """
    
    config = get_config()
    cache_file = config.cache_dir / "feature_ideas.json"
    ideas_dir = config.output_dir / "ideas"
    
    # Check cache
    if use_cache and cache_file.exists():
        try:
            with open(cache_file) as f:
                cached = json.load(f)
                if verbose:
                    print("Using cached feature ideas")
                return cached
        except Exception:
            pass
    
    if verbose:
        print("="*60)
        print("FEATURE IDEATION")
        print("="*60)
    
    # Get capabilities if not provided
    if capabilities_summary is None:
        if project_path:
            from crowdmind.research.codebase import get_capabilities_summary
            if verbose:
                print("  Loading codebase capabilities...")
            capabilities_summary = get_capabilities_summary(project_path)
        else:
            capabilities_summary = "No codebase analysis available."
    
    # Get pain points if not provided
    if pain_points_summary is None:
        from crowdmind.research.multi import get_multi_research_summary
        if verbose:
            print("  Loading pain points from research...")
        pain_points_summary = get_multi_research_summary()
    
    # Generate ideas
    ideas = generate_feature_ideas(
        capabilities_summary=capabilities_summary,
        pain_points_summary=pain_points_summary,
        num_ideas=num_ideas,
        verbose=verbose,
    )
    
    if not ideas:
        print("ERROR: No ideas generated")
        return {"ideas": [], "files": []}
    
    if verbose:
        print(f"\nGenerated {len(ideas)} feature ideas:")
        for idea in ideas:
            star_score = idea.get('star_potential', {}).get('score', 0)
            effort = idea.get('implementation', {}).get('estimated_effort', '?')
            print(f"  [{star_score}/10] {idea.get('name')} ({effort})")
    
    # Save to files
    if verbose:
        print(f"\nSaving idea files...")
    
    files = save_idea_files(ideas, ideas_dir, verbose=verbose)
    
    result = {
        "timestamp": datetime.now().isoformat(),
        "num_ideas": len(ideas),
        "ideas": ideas,
        "files": files,
    }
    
    # Cache
    config.cache_dir.mkdir(parents=True, exist_ok=True)
    with open(cache_file, 'w') as f:
        json.dump(result, f, indent=2)
    
    if verbose:
        print(f"\nFeature ideation complete!")
        print(f"Ideas saved to: {ideas_dir}")
    
    return result


def get_top_ideas(n: int = 3) -> List[Dict]:
    """Get top N ideas by star potential."""
    
    config = get_config()
    cache_file = config.cache_dir / "feature_ideas.json"
    
    if cache_file.exists():
        with open(cache_file) as f:
            data = json.load(f)
            ideas = data.get('ideas', [])
            
            # Sort by star potential
            ideas.sort(
                key=lambda x: x.get('star_potential', {}).get('score', 0),
                reverse=True
            )
            
            return ideas[:n]
    
    return []


def get_ideas_summary() -> str:
    """Get summary of ideas for prompts."""
    
    ideas = get_top_ideas(5)
    
    if not ideas:
        return "No feature ideas generated yet. Run ideation first."
    
    summary = "## Top Feature Ideas\n\n"
    
    for idea in ideas:
        star = idea.get('star_potential', {}).get('score', 0)
        effort = idea.get('implementation', {}).get('estimated_effort', '?')
        summary += f"### {idea.get('name')} [{star}/10 stars, {effort} effort]\n"
        summary += f"**Problem:** {idea.get('problem', '')[:100]}...\n"
        summary += f"**Solution:** {idea.get('solution', '')[:100]}...\n\n"
    
    return summary


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Generate feature ideas")
    parser.add_argument("--project", help="Path to project")
    parser.add_argument("--num", type=int, default=5, help="Number of ideas")
    parser.add_argument("--no-cache", action="store_true", help="Skip cache")
    parser.add_argument("--top", type=int, help="Show top N ideas")
    args = parser.parse_args()
    
    if args.top:
        ideas = get_top_ideas(args.top)
        for idea in ideas:
            star = idea.get('star_potential', {}).get('score', 0)
            print(f"\n[{star}/10] {idea.get('name')}")
            print(f"  {idea.get('tagline')}")
            print(f"  Problem: {idea.get('problem', '')[:80]}...")
    else:
        run_ideation(
            project_path=args.project,
            num_ideas=args.num,
            use_cache=not args.no_cache,
        )
